language: node_js
sudo: required
node_js:
- '6'
before_install:
- sh etc/travis-setup.sh
env:
  global:
  - secure: CsEA+u9PRROrLX9PHYi6oEx/sNZaY8Bgzxqkxzt24ikAvzBC7RYjZFLppCTWz8oqDS1DwQIqVY44ugmSHmsUrXs6Ih/twlDHNJ1nhGmNuGjm2XaLzqOoxSppAeDkaEgc6N3ahjSN6umnpn2GugWcc9z4egYhsKUxZ0RPum84tLm+pG6UGZThNCSgdSCxp5Eyv66ownQRAnQQPoe9QixHO86d/AnxV6tzdMGwf1XQV/19lTH/nPu/V3hQzJOSjpJNF2azurID4NnHQM1ZOZfe4+BFSb0hcIHw6B0IRnUHLLZVpuvRkl0SQUPbvtxrPMeFRELmAoH8/0niU9UjWgHoV50wCcvUtBu0imtxHpBMF0AJKJNJLXer+1pk2hKMMbO0iTq3sytJ4ClZFb0NmyjBL97xpnzRjsJS7C69DzcB7iEdhRJPwRZ53kEUQEmQpr1NbtpBarIZzcQh3rHZjgGOMdbA7OxhjZ0ueMYJcRtGAcMiyRFPewzDNJkLmYlDmYRlcHIRk+sLZrvBgc2OxlFf5sAALEVs5EWmFPoxPhbbMQbT46aZJT32cs6Aw3gBDPKxOdh9zyIBvsegPQGRYp8BzJR1o72fqwk+4QfEDOodgi50/73gQgtb8o7TJJ+61LuFXRhQz1FObO+4egyUEHh5ciJeo5IXiOyaHgAK6UqiAwg=
