language: node_js
sudo: required
dist: trusty
node_js:
- 'node'
before_install:
- bash etc/ci-setup.sh
script: yarn test
matrix:
  fast_finish: true
  include:
    - jdk: openjdk7
    - jdk: oraclejdk8
    - jdk: oraclejdk9
